Develop
Noskovsk/java-explore-with-me pull request #2
Opened 2023-01-07 21:31 UTC by Noskovsk

2023-01-08 18:41 UTC, db-exp requested changes

2023-01-08 18:41 UTC, db-exp commented on explore-main/pom.xml
> +    <properties>
нужно перенести это в parent pom

2023-01-08 18:41 UTC, db-exp commented on explore-main/pom.xml
> +            <version>2.8.8</version>
конкретные версии должны быть указаны в dependencyManagement в parent pom'е

2023-01-08 18:41 UTC, db-exp commented on explore-statistic/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
интересный способ записи, который как по мне очень неудобно читать)
Но коммент немного про другое - добавь к varchar явную размерность, пожалуйста

2023-01-08 18:41 UTC, db-exp commented on explore-statistic/pom.xml
> +            <version>1.18.24</version>
конкретные версии должны быть в dependencyManagement parent'а

2023-01-08 18:41 UTC, db-exp commented on explore-statistic/pom.xml
> +    <properties>
такое лучше в parent pom'е держать

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/model/Category.java
> +    private String name;
Давай добавим Size как в sql скрипте

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/dto/user/UserDto.java
> +public class UserDto {
Давай добавим Size на String как в sql скрипте

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/LocationRepository.java
> +public interface LocationRepository extends JpaRepository<Location, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/PartRequestRepository.java
> +public interface PartRequestRepository extends JpaRepository<ParticipationRequest, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Нужно добавить аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/model/User.java
> +        //System.out.println("EQUALS");
давай удалим ненужный код

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/model/User.java
> +public class User {
хорошо бы добавить Size/Null/NotBlank итд согласно логике на String поля

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Нельзя участвовать в неопубликованном событии!");
ну тут не совсем Forbidden (доступ запрещен), а скорее BadRequest

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Достигнут лимит по количеству участников в событии!");
лучше подойдет BadRequest

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Подтвердить заявку можно только из статуса PENDING!");
лучше BadRequest

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.FORBIDDEN, "остигнут лимит по количеству участников в событии!");
BadRequest

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Отклонять заявку можно только из статуса PENDING!");
BadRequest

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +public class ParticipationRequestServiceImpl implements ParticipationRequestService {
Я бы перенес конкретные ошибки Respons'а в глобальный обработчик, а тут кидал бы кастомные исключения. Чтобы сервис не знал ничего о слое контроллера

2023-01-08 18:41 UTC, db-exp commented on explore-statistic/src/main/java/ru/practicum/exploreit/statistic/repository/StatisticRepository.java
> +public interface StatisticRepository extends JpaRepository<EndpointHit, Long> {
Давай добавим аннотацию Repository

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/model/Compilation.java
> +    private String title;
Давай добавим аннотацию Size и NotBlank/Nullable итп

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +public class ErrorHandler {
Кажется, что лучше сюда перенести обработку ошибок с проставлением статуса  - 403, 400, 404 итд

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +    public EventFullDto getEventInfo(Long eventId, HttpServletRequest request) throws InterruptedException {
лучше передать сюда данные из request, но не сам request, чтобы не смешивать слои

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/model/Event.java
> +public class Event {
Давай добавим аннотации валидации на String как в sql - размер (Size), null/не null

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +public class EventServiceImpl {
тут тоже общий совет - использовать кастомные exception унаследованные от RuntimeException и конкретные статусы ставить уже на уровне обработчика

2023-01-08 18:41 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +    public List<EventFullDto> getEventsByFilter(HttpServletRequest request,
Давай не будем сюда передавать сам HttpServletRequest, а только данные из него

2023-01-09 15:00 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +    public List<EventFullDto> getEventsByFilter(HttpServletRequest request,
Готово

2023-01-09 15:00 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +public class EventServiceImpl {
Готово

2023-01-09 15:00 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/model/Event.java
> +public class Event {
Готово

2023-01-09 15:00 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +    public EventFullDto getEventInfo(Long eventId, HttpServletRequest request) throws InterruptedException {
Готово

2023-01-09 15:01 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +public class ErrorHandler {
Готово

2023-01-09 15:01 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/model/Compilation.java
> +    private String title;
Готово

2023-01-09 15:01 UTC, Noskovsk commented on explore-statistic/src/main/java/ru/practicum/exploreit/statistic/repository/StatisticRepository.java
> +public interface StatisticRepository extends JpaRepository<EndpointHit, Long> {
Готово

2023-01-09 15:01 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +public class ParticipationRequestServiceImpl implements ParticipationRequestService {
Готово

2023-01-09 15:01 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Отклонять заявку можно только из статуса PENDING!");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.FORBIDDEN, "остигнут лимит по количеству участников в событии!");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Подтвердить заявку можно только из статуса PENDING!");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Достигнут лимит по количеству участников в событии!");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Нельзя участвовать в неопубликованном событии!");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/model/User.java
> +public class User {
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/model/User.java
> +        //System.out.println("EQUALS");
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Готово

2023-01-09 15:02 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/PartRequestRepository.java
> +public interface PartRequestRepository extends JpaRepository<ParticipationRequest, Long> {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/LocationRepository.java
> +public interface LocationRepository extends JpaRepository<Location, Long> {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/dto/user/UserDto.java
> +public class UserDto {
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/model/Category.java
> +    private String name;
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-statistic/pom.xml
> +    <properties>
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-statistic/pom.xml
> +            <version>1.18.24</version>
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-statistic/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
Нда, как то странно отработал автоформат в idea. Пересоздал файл, все ок, и добавил размерность.

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/pom.xml
> +            <version>2.8.8</version>
Готово

2023-01-09 15:03 UTC, Noskovsk commented on explore-main/pom.xml
> +    <properties>
Готово

2023-01-09 19:42 UTC, db-exp requested changes

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +        return Map.of("error", "Object not found: " + e.getMessage());
ну тут не совсем object not found) скорее какая-то проблема с данными

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
остался ReposneStatusException
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +public class ErrorHandler {
403 еще не хватает для случаев когда лезем в чужое событие/запрос итп

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
остался ReposneStatusException
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
остался ReposneStatusException
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Запрашивать информацию может только инициатор события!");
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Отменить запрос может только инициатор запроса!");
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Акцептовать заявки может только инициатор события!");
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Отклонять заявки может только инициатор события!");
Такие ошибки должны быть все таки не BadRequest, а что-то типа ForbiddenException c кодом 403 в конечном ответе

2023-01-09 19:42 UTC, db-exp commented on explore-statistic/pom.xml
> +            <version>6.2.3.Final</version>
конкретные версии должны быть в parent - в dependencyManagement

2023-01-10 04:17 UTC, Noskovsk commented on explore-statistic/pom.xml
> +            <version>6.2.3.Final</version>
Готово

2023-01-10 04:25 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +public class ErrorHandler {
Готово

2023-01-10 04:26 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/exception/ErrorHandler.java
> +        return Map.of("error", "Object not found: " + e.getMessage());
Готово

2023-01-10 04:28 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
Готово

2023-01-10 04:29 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
Готово

2023-01-10 04:29 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/event/EventServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Доступ к события чужих пользователей запрещен!");
Готово

2023-01-10 04:30 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Запрашивать информацию может только инициатор события!");
Понял. Исправил

2023-01-10 04:31 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Отменить запрос может только инициатор запроса!");
Исправил

2023-01-10 04:32 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Акцептовать заявки может только инициатор события!");
Исправил

2023-01-10 04:33 UTC, Noskovsk commented on explore-main/src/main/java/ru/practicum/exploreit/service/participationrequest/ParticipationRequestServiceImpl.java
> +            throw new BadRequestException("Отклонять заявки может только инициатор события!");
Исправлено

2023-01-10 12:07 UTC, db-exp approved these changes

2023-01-12 16:08 UTC, merged